name: Weekly Telegram Report

on:
  schedule:
    # ë§¤ì£¼ í† ìš”ì¼ 18:00 (UTC, í•œêµ­ì€ +9ì‹œê°„ = 03:00 ì¼ìš”ì¼)
    - cron: '0 9 * * 6'
    # ë§¤ì¼ 08:00 (UTC, í•œêµ­ì€ +9ì‹œê°„ = 17:00)
    - cron: '0 15 * * *'  # ë§¤ì¼ ì˜¤ì „ 09:00 PST
  workflow_dispatch:      # ìˆ˜ë™ ì‹¤í–‰ë„ ê°€ëŠ¥í•˜ê²Œ ì„¤ì •

jobs:
  run-daily-gpt:
    if: github.event.schedule == '0 15 * * *' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ ì €ì¥ì†Œ ì²´í¬ì•„ì›ƒ
        uses: actions/checkout@v3

      - name: ğŸ íŒŒì´ì¬ ì„¤ì¹˜
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: ğŸ“¦ ì˜ì¡´ì„± ì„¤ì¹˜
        run: |
          pip install openai fpdf2 yagmail time python-dotenv yfinance deep_translator matplotlib PyPDF2 pandas_datareader pd bs4 seaborn

      - name: ğŸ“¤ GPT â†’ Message
        run: |
          python daily_support_me.py
          python daily_support_afternoon.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

  run-weekly-gpt:
    if: github.event.schedule == '0 9 * * 6'  || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ ì €ì¥ì†Œ ì²´í¬ì•„ì›ƒ
        uses: actions/checkout@v3

      - name: ğŸ íŒŒì´ì¬ ì„¤ì¹˜
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: ğŸ“¦ ì˜ì¡´ì„± ì„¤ì¹˜
        run: |
          pip install openai fpdf2 yagmail python-dotenv time yfinance deep_translator matplotlib PyPDF2 pandas_datareader pd bs4 seaborn

      - name: ğŸ“¤ GPT â†’ Message
        run: |
          python sibling_message.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          
